# building app and required component for running the app
version: '3.3'
services:
  database:
    build: docker/mysql
    ports:
      - "33061:3306"
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - devnetwork
  web:
    image: laravel-nginx-1.0.3
    container_name: laravel-www
    build: docker/nginx
    ports:
      - "8888:80"
    # we have configured our nginx container to have its webroot /var/www/public
    # so we have to mount our project "example-proj" folder to /var/www
    # we already have "public" folder in our project
    volumes:
      - ./:/var/www/html
    links:
      - app
    depends_on:
      - app
    networks:
      - devnetwork
  app:
    image: laravel-phpfpm-1.0.3
    build: docker/app
    volumes:
      - ./:/var/www/html
    expose:
      - "9000"
    links:
      - redis
      - database
    networks:
      - devnetwork
  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - devnetwork
volumes:
  mysql_data:
  redis_data:
networks:
  devnetwork: